def show_menu():
    print("\n=== Biblioteca MVC ===")
    print("1. Agregar autor")
    print("2. Agregar editorial")
    print("3. Agregar libro")
    print("4. Agregar prestatario")
    print("5. Prestar libro")
    print("6. Listar autores")
    print("7. Listar editoriales")
    print("8. Listar libros")
    print("9. Listar prestatarios")
    print("10. Actualizar entidad")
    print("11. Eliminar entidad")
    print("0. Salir")
